spring:
    application:
        name: companie
    datasource:
        hikari:
            connection-timeout: 20000
            maximum-pool-size: 5
        password: root
        url: jdbc:postgresql://localhost:5432/companies
        username: root